package me.uc_hussein.ultrastpa.gui;
import me.uc_hussein.ultrastpa.ULTRASTPAPlugin; import me.uc_hussein.ultrastpa.model.*; import me.uc_hussein.ultrastpa.util.*;
import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.event.inventory.InventoryClickEvent; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.SkullMeta;
import java.util.*;
import java.util.stream.Collectors;
public final class TPAGui {
 private final ULTRASTPAPlugin plugin; public TPAGui(ULTRASTPAPlugin p){plugin=p;}
 private String title(String key){return plugin.messages().raw("prefix").replace("&4&lULTRAS MC &8| ","")+plugin.messages().raw(key);}
 public void openSelector(Player p,int page){List<? extends Player> ps=Bukkit.getOnlinePlayers().stream().filter(x->!x.equals(p)).sorted(Comparator.comparing(Player::getName,String.CASE_INSENSITIVE_ORDER)).toList(); int size=27; Inventory inv=Bukkit.createInventory(new Holder("selector",null,page),size,ColorUtil.component(plugin.getConfig().getString("gui.selector-title","&8ULTRAS MC &7• &bPlayers"))); int start=page*21; int[] slots=plugin.getConfig().getIntegerList("gui.player-slots").stream().mapToInt(Integer::intValue).toArray(); for(int i=0;i<slots.length&&start+i<ps.size();i++){Player t=ps.get(start+i);inv.setItem(slots[i],head(t,profileName(t)));} inv.setItem(plugin.getConfig().getInt("gui.back-slot",22),ItemUtil.item(Material.BARRIER,plugin.messages().raw("back"))); if(start+21<ps.size())inv.setItem(plugin.getConfig().getInt("gui.next-slot",26),ItemUtil.item(Material.ARROW,plugin.messages().raw("next"))); if(page>0)inv.setItem(plugin.getConfig().getInt("gui.previous-slot",18),ItemUtil.item(Material.ARROW,plugin.messages().raw("previous"))); p.openInventory(inv);}
 private String profileName(Player t){String c=plugin.messages().raw("profile-coordinates").replace("%coordinates%",coords(t)); return "&d"+t.getName()+" &8• "+c;}
 private String coords(Player t){Location l=t.getLocation();return plugin.getConfig().getString("format.coordinates","X: %x% Y: %y% Z: %z%").replace("%x%",String.valueOf(l.getBlockX())).replace("%y%",String.valueOf(l.getBlockY())).replace("%z%",String.valueOf(l.getBlockZ()));}
 private ItemStack head(Player p,String name){ItemStack i=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)i.getItemMeta();m.setOwningPlayer(p);m.displayName(ColorUtil.component(name));m.lore(List.of(ColorUtil.component(plugin.messages().raw("profile-online")),ColorUtil.component(plugin.messages().raw("profile-world").replace("%world%",p.getWorld().getName())),ColorUtil.component(plugin.messages().raw("profile-coordinates").replace("%coordinates%",coords(p)))));i.setItemMeta(m);return i;}
 public void openProfile(Player viewer,Player target){Inventory inv=Bukkit.createInventory(new Holder("profile",target.getUniqueId(),0),27,ColorUtil.component(plugin.getConfig().getString("gui.profile-title","&8ULTRAS MC &7• &bProfile")));inv.setItem(13,head(target,"&d&l"+target.getName()));inv.setItem(12,ItemUtil.item(Material.ENDER_PEARL,plugin.messages().raw("tpahere-to")));inv.setItem(14,ItemUtil.item(Material.ENDER_EYE,plugin.messages().raw("teleport-to")));inv.setItem(22,ItemUtil.item(Material.BARRIER,plugin.messages().raw("back")));viewer.openInventory(inv);}
 public void openRequest(Player target,TeleportRequest r){Player sender=Bukkit.getPlayer(r.sender());if(sender==null)return;Inventory inv=Bukkit.createInventory(new Holder("request",r.sender(),0),27,ColorUtil.component(plugin.getConfig().getString("gui.request-title","&8ULTRAS MC &7• &bRequest")));inv.setItem(13,head(sender,"&d&l"+sender.getName()));inv.setItem(11,ItemUtil.item(Material.LIME_DYE,plugin.messages().raw("accept")));inv.setItem(15,ItemUtil.item(Material.RED_DYE,plugin.messages().raw("deny")));inv.setItem(13,head(sender,"&d&l"+sender.getName()));inv.setItem(22,ItemUtil.item(Material.GRAY_DYE,plugin.messages().raw("block")));inv.setItem(26,ItemUtil.item(Material.BARRIER,plugin.messages().raw("back")));target.openInventory(inv);}
 public record Holder(String type,UUID target,int page) implements InventoryHolder {public Inventory getInventory(){return null;}}
}
