package me.uc_hussein.ultrastpa.command;
import me.uc_hussein.ultrastpa.ULTRASTPAPlugin;import me.uc_hussein.ultrastpa.gui.TPAGui;import me.uc_hussein.ultrastpa.model.RequestType;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class TPACommand implements CommandExecutor,TabCompleter {private final ULTRASTPAPlugin p;public TPACommand(ULTRASTPAPlugin p){this.p=p;}
 public boolean onCommand(CommandSender s,Command c,String label,String[] a){if(!(s instanceof Player pl)){p.messages().send(s,"player-only");return true;}p.data().ensure(pl.getUniqueId());if(p.isWorldDisabled(pl.getWorld())&&!pl.isOp()){p.messages().send(pl,"world-disabled");return true;}if(a.length==0){new TPAGui(p).openSelector(pl,0);return true;}String sub=a[0].toLowerCase();
  if(sub.equals("reload")){if(!pl.hasPermission("ultrastpa.admin")){p.messages().send(pl,"no-permission");return true;}p.reloadAll();p.messages().send(pl,"reload");return true;}
  if(sub.equals("accept")||sub.equals("قبول")){p.accept(pl);return true;} if(sub.equals("deny")||sub.equals("reject")||sub.equals("رفض")){p.deny(pl);return true;} if(sub.equals("cancel")||sub.equals("إلغاء")){if(a.length>1){Player t=Bukkit.getPlayerExact(a[1]);if(t==null){p.messages().send(pl,"unknown-player","%player%",a[1]);return true;}p.requests().cancelSender(pl,t);}else p.requests().cancelLatest(pl);return true;}
  if(sub.equals("toggle")){boolean v=!p.data().getBool(pl.getUniqueId(),"receive-tpa",true);p.data().setBool(pl.getUniqueId(),"receive-tpa",v);p.messages().send(pl,"setting-tpa","%state%",p.messages().state(v));return true;}
  if(sub.equals("togglehere")){boolean v=!p.data().getBool(pl.getUniqueId(),"receive-tpahere",true);p.data().setBool(pl.getUniqueId(),"receive-tpahere",v);p.messages().send(pl,"setting-tpahere","%state%",p.messages().state(v));return true;}
  if(sub.equals("toggleall")){boolean v=!p.data().getBool(pl.getUniqueId(),"receive-all",true);p.data().setBool(pl.getUniqueId(),"receive-all",v);p.messages().send(pl,"setting-all","%state%",p.messages().state(v));return true;}
  if(sub.equals("auto")){boolean v=!p.data().getBool(pl.getUniqueId(),"auto-accept",false);p.data().setBool(pl.getUniqueId(),"auto-accept",v);p.messages().send(pl,"setting-auto","%state%",p.messages().state(v));return true;}
  if(sub.equals("gui")){boolean v=!p.data().getBool(pl.getUniqueId(),"open-gui",true);p.data().setBool(pl.getUniqueId(),"open-gui",v);p.messages().send(pl,"setting-gui","%state%",p.messages().state(v));return true;}
  if(sub.equals("block")||sub.equals("unblock")){if(a.length<2){p.messages().send(pl,"usage");return true;}Player t=Bukkit.getPlayerExact(a[1]);if(t==null){p.messages().send(pl,"unknown-player","%player%",a[1]);return true;}boolean set=sub.equals("block");if(p.data().isBlocked(pl.getUniqueId(),t.getUniqueId())==set){p.messages().send(pl,set?"already-blocked":"not-blocked","%player%",t.getName());return true;}p.data().setBlocked(pl.getUniqueId(),t.getUniqueId(),set);p.messages().send(pl,set?"blocked":"unblocked","%player%",t.getName());return true;}
  if(sub.equals("all")){if(!p.getConfig().getBoolean("settings.allow-tpa-all",true)){p.messages().send(pl,"all-disabled");return true;}p.sendAll(pl);return true;}
  Player target=Bukkit.getPlayerExact(a[0]);if(target==null){p.messages().send(pl,"unknown-player","%player%",a[0]);return true;}p.sendTPA(pl,target);return true;}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1){List<String>x=new ArrayList<>(List.of("all","accept","deny","cancel","toggle","togglehere","toggleall","auto","gui","block","unblock"));if(s.hasPermission("ultrastpa.admin"))x.add("reload");String q=a[0].toLowerCase();Bukkit.getOnlinePlayers().forEach(pl->{if(pl!=s)x.add(pl.getName());});return x.stream().filter(z->z.toLowerCase().startsWith(q)).distinct().sorted().toList();}if(a.length==2&&(a[0].equalsIgnoreCase("cancel")||a[0].equalsIgnoreCase("block")||a[0].equalsIgnoreCase("unblock"))){return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(n->n.toLowerCase().startsWith(a[1].toLowerCase())).sorted().toList();}return List.of();}
}
