package me.uc_hussein.ultrastpa;

import me.uc_hussein.ultrastpa.command.*;import me.uc_hussein.ultrastpa.listener.GuiListener;import me.uc_hussein.ultrastpa.model.RequestType;import me.uc_hussein.ultrastpa.service.*;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.plugin.java.JavaPlugin;
import java.io.File;import java.util.*;import java.util.concurrent.ConcurrentHashMap;

public final class ULTRASTPAPlugin extends JavaPlugin {
 private PlayerDataService data; private LogService logs; private MessageService messages; private RequestService requests; private final Map<UUID,Long> cooldown=new ConcurrentHashMap<>();
 @Override public void onEnable(){saveDefaultConfig();saveResource("lang/en.yml",false);saveResource("lang/ar.yml",false);reloadAll();TPACommand cmd=new TPACommand(this);Objects.requireNonNull(getCommand("tpa")).setExecutor(cmd);Objects.requireNonNull(getCommand("tpa")).setTabCompleter(cmd);var here=new SimpleCommand(this,"here"); Objects.requireNonNull(getCommand("tpahere")).setExecutor(here); Objects.requireNonNull(getCommand("tpahere")).setTabCompleter((sender,command,label,args)->args.length==1?getServer().getOnlinePlayers().stream().map(Player::getName).filter(n->!n.equalsIgnoreCase(sender.getName())).filter(n->n.toLowerCase().startsWith(args[0].toLowerCase())).sorted().toList():List.of());Objects.requireNonNull(getCommand("tpaccept")).setExecutor(new SimpleCommand(this,"accept"));Objects.requireNonNull(getCommand("tpdeny")).setExecutor(new SimpleCommand(this,"deny"));Objects.requireNonNull(getCommand("tpcancel")).setExecutor(new SimpleCommand(this,"cancel"));getServer().getPluginManager().registerEvents(new GuiListener(this),this);getLogger().info("ULTRAS_TPA 1.0.0 by UC_Hussein enabled.");}
 public void reloadAll(){reloadConfig();data=new PlayerDataService(this);logs=new LogService(this);messages=new MessageService(this);if(requests==null)requests=new RequestService(this);}
 public PlayerDataService data(){return data;}public LogService loggerService(){return logs;}public MessageService messages(){return messages;}public RequestService requests(){return requests;}public Server server(){return getServer();}
 public int seconds(String path){return Math.max(0,getConfig().getInt(path,0));}
 public boolean isWorldDisabled(World w){return getConfig().getStringList("worlds.disabled-worlds").contains(w.getName());}
 public void log(String a,String d){if(logs!=null)logs.log(a,d);}
 public boolean canSend(Player sender,Player target,RequestType type){if(sender.equals(target)&&!getConfig().getBoolean("settings.allow-self-request",false)){messages.send(sender,"self-request");return false;}if(isWorldDisabled(sender.getWorld())||isWorldDisabled(target.getWorld())){messages.send(sender,"world-disabled");return false;}if(data.isBlocked(target.getUniqueId(),sender.getUniqueId())){messages.send(sender,"blocked-by-target","%player%",target.getName());return false;}String key=switch(type){case TPA->"receive-tpa";case TPAHERE->"receive-tpahere";case TPA_ALL->"receive-all";};if(!data.getBool(target.getUniqueId(),key,true)){messages.send(sender,switch(type){case TPA->"receive-tpa-off";case TPAHERE->"receive-tpahere-off";case TPA_ALL->"receive-all-off";});return false;}long cd=seconds("settings.request-cooldown-seconds")*1000L;Long last=cooldown.get(sender.getUniqueId());if(last!=null&&!sender.isOp()&&getConfig().getBoolean("settings.op-bypass-cooldown",true)&&System.currentTimeMillis()-last<cd){messages.send(sender,"cooldown","%time%",String.valueOf(Math.ceil((cd-(System.currentTimeMillis()-last))/1000.0)));return false;}if(!sender.isOp())cooldown.put(sender.getUniqueId(),System.currentTimeMillis());return true;}
 public void sendTPA(Player s,Player t){if(!canSend(s,t,RequestType.TPA))return;requests.send(s,t,RequestType.TPA);messages.send(s,"request-sent","%player%",t.getName(),"%type%",messages.type(RequestType.TPA));}
 public void sendTPAHere(Player s,Player t){if(!canSend(s,t,RequestType.TPAHERE))return;requests.send(s,t,RequestType.TPAHERE);messages.send(s,"request-sent","%player%",t.getName(),"%type%",messages.type(RequestType.TPAHERE));}
 public void sendAll(Player s){int count=0; if(isWorldDisabled(s.getWorld())){messages.send(s,"world-disabled");return;} long cd=seconds("settings.request-cooldown-seconds")*1000L; Long last=cooldown.get(s.getUniqueId()); if(last!=null&&!s.isOp()&&System.currentTimeMillis()-last<cd){messages.send(s,"cooldown","%time%",String.valueOf(Math.ceil((cd-(System.currentTimeMillis()-last))/1000.0)));return;} for(Player t:getServer().getOnlinePlayers()){if(t.equals(s))continue; if(isWorldDisabled(t.getWorld())||data.isBlocked(t.getUniqueId(),s.getUniqueId())||!data.getBool(t.getUniqueId(),"receive-all",true))continue; requests.send(s,t,RequestType.TPA_ALL);count++;} if(!s.isOp())cooldown.put(s.getUniqueId(),System.currentTimeMillis()); messages.send(s,"request-sent-all","%count%",String.valueOf(count));}
 public void accept(Player p){var r=requests.latest(p.getUniqueId());if(r==null){messages.send(p,"no-incoming");return;}new me.uc_hussein.ultrastpa.gui.TPAGui(this).openRequest(p,r);}
 public void deny(Player p){var r=requests.latest(p.getUniqueId());if(r==null){messages.send(p,"no-incoming");return;}new me.uc_hussein.ultrastpa.gui.TPAGui(this).openRequest(p,r);}
 public File languageFile(String lang){return new File(getDataFolder(),"lang/"+lang+".yml");}
 public org.bukkit.configuration.file.YamlConfiguration getLang(){String lang=getConfig().getString("plugin.default-language","en");File f=languageFile(lang);if(!f.exists())f=languageFile("en");return org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(f);}
}
