package me.uc_hussein.ultrastpa.listener;
import me.uc_hussein.ultrastpa.ULTRASTPAPlugin;import me.uc_hussein.ultrastpa.gui.TPAGui;import me.uc_hussein.ultrastpa.gui.TPAGui.Holder;import me.uc_hussein.ultrastpa.model.TeleportRequest;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.inventory.InventoryCloseEvent;import org.bukkit.inventory.ItemStack;
import java.util.*;
public final class GuiListener implements Listener {private final ULTRASTPAPlugin p;public GuiListener(ULTRASTPAPlugin p){this.p=p;}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player pl)||!(e.getInventory().getHolder() instanceof Holder h))return;e.setCancelled(true); if(e.getRawSlot()>=e.getInventory().getSize())return; TPAGui gui=new TPAGui(p);String type=h.type();int slot=e.getRawSlot();
  if(type.equals("selector")){if(slot==p.getConfig().getInt("gui.back-slot",22)){pl.closeInventory();return;} if(slot==p.getConfig().getInt("gui.next-slot",26)){gui.openSelector(pl,h.page()+1);return;}if(slot==p.getConfig().getInt("gui.previous-slot",18)){gui.openSelector(pl,Math.max(0,h.page()-1));return;} ItemStack it=e.getCurrentItem();if(it!=null&&it.getType()==Material.PLAYER_HEAD&&it.getItemMeta()!=null&&it.getItemMeta().getDisplayName()!=null){String n=it.getItemMeta().getDisplayName().replace("§d","").replace("§l","").split(" ")[0];Player target=Bukkit.getPlayerExact(n);if(target!=null)gui.openProfile(pl,target);} }
  else if(type.equals("profile")){Player target=Bukkit.getPlayer(h.target());if(target==null){pl.closeInventory();return;}if(slot==22){gui.openSelector(pl,0);return;}if(slot==14){p.sendTPA(pl,target);pl.closeInventory();}if(slot==12){p.sendTPAHere(pl,target);pl.closeInventory();}}
  else if(type.equals("request")){TeleportRequest r=p.requests().latest(pl.getUniqueId());if(r==null){p.messages().send(pl,"no-incoming");pl.closeInventory();return;}if(!r.sender().equals(h.target())){p.messages().send(pl,"no-request-from","%player%",Bukkit.getOfflinePlayer(h.target()).getName());return;}if(slot==11){p.requests().accept(pl,r);pl.closeInventory();}else if(slot==15){p.requests().deny(pl,r);pl.closeInventory();}else if(slot==22){p.data().setBlocked(pl.getUniqueId(),r.sender(),true);p.messages().send(pl,"blocked","%player%",Bukkit.getOfflinePlayer(r.sender()).getName());p.requests().deny(pl,r);pl.closeInventory();}else if(slot==26){pl.closeInventory();}}
 }
}
